import os

from dotenv import load_dotenv

from api_server import send_email_report

# Load the environment variables from .env
load_dotenv('.env', override=True)

print("Testing Email Configuration...")
print(f"SMTP_EMAIL: {os.environ.get('SMTP_EMAIL')}")
print(f"SMTP_PASSWORD: {'*** SET ***' if os.environ.get('SMTP_PASSWORD') else '*** MISSING ***'}")

if not os.environ.get('SMTP_EMAIL') or not os.environ.get('SMTP_PASSWORD'):
    print("\nERROR: You must set SMTP_EMAIL and SMTP_PASSWORD in your .env file first!")
    exit(1)

# Sample Executive Summary (shown in UI and email body)
test_summary = """
### Executive Summary & Recommendation
- **Verdict**: Bullish (Strong Buy)
- **Target Price**: $210.00 (Current: $178.50)
- **Time Horizon**: 3-6 Months
- **Key Catalyst**: Robust Q3 cloud revenue growth and expanding operating margins.
"""

# Sample Full Master Report (attached as PDF)
test_master_report = """
# Trading Agents Consolidated Master Report: AAPL

**Ticker:** AAPL\n
**Date:** 2026-09-10\n
**Generated By:** Trading Agents Multi-Agent Framework


---

## I. Executive Summary
The multi-agent consensus indicates a high-conviction bullish bias for Apple Inc. (AAPL). Technical momentum is well supported by expanding enterprise services revenue and steady iPhone replacement cycles.

## II. Fundamental Analysis
- **Revenue Growth**: 8.2% YoY driven by Services & Wearables.
- **Operating Margin**: Expanded 140 bps to 31.2%.
- **Free Cash Flow**: $108B over TTM, supporting continued share buybacks and dividend growth.
- **P/E Ratio**: 28.4x, slightly elevated relative to historical median but justified by margin expansion.

## III. Technical Analysis
- **200-Day SMA**: Price is trading comfortably above both the 50-day and 200-day moving averages.
- **RSI (14)**: Current reading at 58.4, displaying strong momentum without entering overbought territory.
- **MACD**: Bullish crossover confirmed on weekly timeframe.
- **Support & Resistance**: Key support established at $170.00; initial resistance identified at $185.00.

## IV. Sentiment & News Analysis
- Market sentiment remains positive across major financial outlets.
- Institutional accumulation detected over the preceding 4 weeks.
- Supply chain checks in Asia suggest steady component orders for next-gen models.

## V. Risk Management Team Debate
- **Conservative Analyst**: Expressed caution regarding consumer hardware elongation cycles and geopolitical supply chain sensitivities. Recommended a trailing stop-loss at $168.00.
- **Aggressive Analyst**: Highlighted AI on-device capabilities and potential new high-margin subscription tiers. Urged full capital allocation.
- **Neutral Analyst**: Balanced risk/reward favoring 60% standard position sizing.

## VI. Portfolio Manager Final Decision
Approved entry with standard position sizing. Set take-profit orders at $205.00 and stop-loss at $168.00. Monitor next quarterly earnings report for service margin sustainability.
"""

print("\nAttempting to send email with short summary in body and full Master Report as PDF...")
try:
    send_email_report("AAPL", "2026-09-10", test_summary, test_master_report)
    print("\n✅ Test complete! Email delivered. Check your hello@manikumarsingh.com inbox.")
except Exception as e:
    print(f"\n❌ Test failed! Error: {e}")

